spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name:
jwt:
  key: 